GET http://localhost:5273

###
GET http://localhost:5273/games

###
GET http://localhost:5273/games/2

###
POST http://localhost:5273/games
Content-Type: application/json

{
  "name": "GTA San Andreas",
  "genreId": 1,
  "price": 26.95,
  "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5273/games/2
Content-Type: application/json

{
    "name": "GTA V",
    "genreId": 1,
    "price": 59.99,
    "releaseDate": "2025-01-01"
}

### 
DELETE http://localhost:5273/games/6